In [1]:
# Python 3.x
%pip install torch torchvision

  Using cached torch-2.11.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (29 kB)
  Using cached torchvision-0.26.0-cp313-cp313-macosx_12_0_arm64.whl.metadata (5.5 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.6/80.6 MB 901.0 kB/s eta 0:00:0000:0100:03
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 584.6 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [torchvision] [torchvision]
Note: you may need to restart the kernel to use updated packages.


In [ ]:
import torch

x = torch.rand(4, 3) # four stacks of three dimensional vectors

print(x)

tensor([[0.2089, 0.3260, 0.3048],
        [0.4458, 0.3646, 0.5682],
        [0.0256, 0.0514, 0.1371],
        [0.3205, 0.8863, 0.3664]])


In [ ]:
shape = (2,3,)    # 2 stacks of three dimensional vectors
rand_tensor = torch.rand(shape) # datatype is float , value between 0 and 1
ones_tensor = torch.ones(shape) # 2 stacks of three dimensional vectors filled with ones
zeros_tensor = torch.zeros(shape) # 2 stacks of three dimensional vectors filled with zeros

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.8746, 0.7198, 0.8213],
        [0.6209, 0.0784, 0.2699]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
tensor = torch.rand(3,4)   # create a random tensor of shape (3,4)

#tensor attributes
print(f"Shape of tensor: {tensor.shape} \n")  # shape of the tensor
print(f"Datatype of tensor: {tensor.dtype} \n") 
print(f"Device tensor is stored on: {tensor.device} \n") # device on which the tensor is stored

Shape of tensor: torch.Size([3, 4]) 

Datatype of tensor: torch.float32 

Device tensor is stored on: cpu 



In [ ]:
tensor = torch.ones(4, 4)

#default datatype is float32

print(f"First row: {tensor[0]}\n")
print(f"First column: {tensor[:, 0]}\n")
print(f"Last column: {tensor[..., -1]}\n")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])

First column: tensor([1., 1., 1., 1.])

Last column: tensor([1., 1., 1., 1.])

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


Standard numpy-like indexing and slicing:

In [ ]:
tensor = torch.ones(4, 4)
# 创建了一个 $4 \times 4$ 的正方形矩阵 (2D)，里面的每一个元素初始化为 1。
# PyTorch 使用逗号分隔维度：tensor[行, 列]。

print(tensor)

print(f"First row: {tensor[0]}")
# 通过 tensor[0]，我们访问了 tensor 的第一行。由于 tensor 是一个 $4 \times 4$ 的矩阵，第一行包含了四个元素，每个元素的值都是 1。

print(f"First column: {tensor[:, 0]}")
# 冒号 : 表示“所有行”，所以这代表获取第 1 列。

print(f"Last column: {tensor[..., -1]}")
#...（Ellipsis）表示忽略前面的所有维度，-1 表示最后一个。在2D情况下，这等同于获取最后一列。

tensor[:,1] = 0 # 第 2 列的值全部改为 0
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


Arithmetic Operations 

In [17]:
# 确认tensor初始值
print(tensor)
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T # python way of doing matrix multiplication
y2 = tensor.matmul(tensor.T) # PyTorch way; matmul() takes one parameter
print (f"y1: \n{y1}\n")
print (f"y2: \n{y2}\n")


#initialization, take the same shape as y1, but fill it with random values

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3) #通常函数会返回一个新的结果，但这里我们告诉 PyTorch：“请把计算结果直接写进我们刚才准备好的 y3 空间里，覆盖掉那些随机数。
# 这是一种节省内存的写法，直接将结果写入已经创建好的 y3 中，而不是产生一个新张量。
print (f"y3: \n{y3}\n")
#在深度学习中，频繁地创建和销毁大张量会非常消耗内存和计算资源。通过使用 out= 参数，我们可以复用已有的内存空间，这在处理大规模数据时能显著提高效率。


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
y1: 
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

y2: 
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

y3: 
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])



In [19]:
# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

print (f"z1: \n{z1}\n")
print (f"z2: \n{z2}\n")

#cool way of initialition 
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print (f"z3: \n{z3}\n")

# summary: 1. element-wise product: * or mul() 2. matrix multiplication: @ or matmul(), pay attention to the dimension. 

z1: 
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

z2: 
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

z3: 
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])



In [ ]:
# use out= to save memory
A = torch.ones(2, 2)
B = torch.zeros(2, 2) # 初始全是 0
torch.add(A, A, out=B)

# data type: float32 

tensor([[2., 2.],
        [2., 2.]])

Single-element tensors 

In [26]:
#print(tensor)
print (f"tensor: {tensor}\n")

agg = tensor.sum() #aggregate 

#print(agg, type(agg)) 
print (f"agg: {agg}, type of agg: {type(agg)}\n") #agg is still a tensor, but it has only one element

agg_item = agg.item() #convert a single-element tensor to a Python number, use item() method

#print(agg_item, type(agg_item))
print (f"agg_item: {agg_item}, type of agg_item: {type(agg_item)}\n")

tensor: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

agg: 12.0, type of agg: <class 'torch.Tensor'>

agg_item: 12.0, type of agg_item: <class 'float'>



In-place operations: Operations that store the result into the operand are called in-place. They are denoted by a _ suffix.

In [27]:
print(f"{tensor} \n")
tensor.add_(5)


print(f"{tensor}")


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


More examples:

In [30]:
x = torch.ones(5)
y = torch.zeros(5)

x

tensor([1., 1., 1., 1., 1.])

In [ ]:
x.copy_(y)
# copied the y into x


print (f"x: {x}\n shape: {x.shape}\n")

x.subtract_(5)
print (f"x: {x}\n shape: {x.shape}\n")

# in place operation: the result is stored in the operand, denoted by _ suffix.


x: tensor([0., 0., 0., 0., 0.])
 shape: torch.Size([5])

x: tensor([-5., -5., -5., -5., -5.])
 shape: torch.Size([5])



NOTE:
In-place operations save some memory, but can be problematic when computing derivatives because of an immediate lossof history. Hence, their use is discouraged.

Tensor to NumPy array

In [ ]:
t = torch.ones(5)
print(f"t: {t}")


n = t.numpy() #use numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


Numpy array to (torch) tensor 

In [46]:
import numpy as np

n = np.ones(5)

print(f"n: {n}\n shape: {n.shape}\n")


t = torch.from_numpy(n)
print(f"t: {t} \n shape: {t.shape}\n")

n: [1. 1. 1. 1. 1.]
 shape: (5,)

t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64) 
 shape: torch.Size([5])

